config/routes.rb
PLReviews::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount JasmineFixtureServer => '/spec/javascripts/fixtures' if defined?(Jasmine::Jquery::Rails::Engine)

  constraints(AuthenticatedConstraint.new) do
    mount Resque::Server, at: '/resque'
  end

  get 'log_in', to: 'sessions#new', as: 'log_in'
  get 'log_out', to: 'sessions#destroy', as: 'log_out'
  get 'sign_up', to: 'users#new', as: 'sign_up'

  # Search routes
  get 'search/autocomplete', to: 'search#autocomplete', as: 'search_autocomplete'
  get 'search/beers', to: 'search#beers', as: 'search_beers'
  get 'search', to: 'search#index', as: 'search'

  # Beer custom routes
  get 'beers/sync', to: 'beers#sync', as: 'sync_beers'
  get 'beers/:id/sync', to: 'beers#sync_beer', as: 'sync_beer'
  get 'breweries/sync', to: 'breweries#sync', as: 'sync_breweries'
  get 'breweries/:id/sync', to: 'breweries#sync_brewery', as: 'sync_brewery'

  get 'beers/random', to: 'beers#random', as: 'random_beer'
  post 'beers/:id/open', to: 'beers#open', as: 'open_beer'

  root to: 'beers#index'

  # BreweryDB API routes
  namespace :api do
    get 'brewery/autocomplete', to: 'breweries#brewery_autocomplete', as: 'brewery_autocomplete'
    get 'brewery/:id/beers', to: 'breweries#brewery_beer_autocomplete', as: 'brewery_beer_autocomplete'
    resources :breweries, only: [:create, :new] do
      resources :beers, only: [:create, :new]
    end
    get 'beers/beer_styles_autocomplete', to: 'beers#beer_styles_autocomplete', as: 'beer_styles_autocomplete'
  end

  # Beer and brewery routes
  resources :beers do
    resources :reviews, only: [:create, :destroy]
  end

  resources :breweries, only: [:index, :show, :new, :create, :destroy] do
    resources :beers, only: [:index, :new]
  end

  # Coffee and Roaster routes
  resources :roasters do
    resources :coffees, only: [:index, :new]
  end

  resources :coffees do
    resources :bags, only: [:index, :new, :create]
    resources :reviews, only: [:create, :destroy]
  end

  post 'bags/:id/open', to: 'bags#open', as: 'open_bag'
  post 'bags/:id/finish', to: 'bags#finish', as: 'finish_bag'
  resources :bags, only: [:destroy]

  # Common routes
  resources :activities, only: [:index, :show]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/bag.rb
class Bag < ActiveRecord::Base
  scope :in_stock, -> { where(finished_at: nil) }

  belongs_to :coffee
  has_one :bag_opened_activity, dependent: :destroy

  validates_presence_of :roasted_on
  validates_presence_of :coffee

  # Opens but does not save bag.
  # Boolean indicating if open successful (i.e. was there an unopened bag)
  def open(current_user)
    return false if self.opened_on

    self.opened_on = Date.parse(Time.now.to_s)
    self.bag_opened_activity = BagOpenedActivity.new(user: current_user, coffee: self.coffee)
    return true
  end

  # Finishes but does not save bag.
  # Boolean indicating if finish successful (i.e. was there an unfinished bag)
  def finish
    return false if self.finished_at || !self.opened_on

    self.finished_at = Date.parse(Time.now.to_s)
    return true
  end
end

app/controllers/bags_controller.rb
class BagsController < ApplicationController
  skip_before_action :require_authentication, only: [:index]
  before_action :set_bag, only: [:show, :destroy, :open, :finish]
  before_action :set_coffee_from_coffee_id, only: [:index, :new, :create]

  # GET /bags
  def index
    @bags = Bag.all.order('roasted_on desc').where(coffee: @coffee).page params[:page]
  end

  # GET /bags/new
  def new
    @bag = Bag.new
  end

  # POST /bags
  def create
    @bag = Bag.new(bag_params)
    @bag.coffee = @coffee

    @bag.bag_opened_activity = BagOpenedActivity.new(user: current_user, coffee: @bag.coffee) if @bag.opened_on

    if @bag.save
      redirect_to coffee_bags_path(@coffee), notice: 'Bag was successfully created.'
    else
      flash.now.alert = 'Failed to save bag.'
      render :new
    end
  end

  def destroy
    coffee = @bag.coffee
    @bag.destroy
    redirect_to coffee_bags_path(coffee)
  end

  def open
    if @bag.open(current_user)
      if @bag.save
        flash.notice = 'Bag was successfully opened.'
      else
        flash.alert = 'Failed to open bag.'
      end
    else
      flash.notice = 'Bag was already opened.'
    end

    redirect_to coffee_bags_path(@bag.coffee)
  end

  def finish
    if @bag.finish
      if @bag.save
        flash.notice = 'Bag was successfully finished.'
      else
        flash.alert = 'Failed to finish bag.'
      end
    else
      flash.notice = 'Bag was already finished or not opened yet.'
    end

    redirect_to coffee_bags_path(@bag.coffee)
  end

  private
  def bag_params
    params.require(:bag).permit(:roasted_on, :coffee_id, :opened_on)
  end

  def set_bag
    @bag = Bag.find(params[:id])
  end

  def set_coffee_from_coffee_id
    @coffee = Coffee.find(params[:coffee_id]) if params[:coffee_id]
  end
end

app/views/admin/bags/_form.html.erb
<div class='new-form'>
    <%= bootstrap_form_for([@coffee, @bag], style: :horizontal) do |f| %>
        <%= f.date_field :roasted_on %>
        <%= f.date_field :opened_on %>
        <%= f.submit 'Add Bag of Coffee', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/admin/bags/_list.html.erb
<small class="visible-xs text-center" style="color: #DDDDDD;">
    Scroll table &rarr;
</small>
<div class="table-responsive">
    <table class='table table-striped'>
        <thead>
        <tr class="info">
            <th>Roasted On</th>
            <th>Opened On</th>
            <th>Finished On</th>
            <% if current_user %>
                <th></th>
            <% end %>
        </tr>
        </thead>

        <tbody>
        <% @bags.each do |bag| %>
            <tr>
                <td><%= bag.roasted_on %></td>
                <td><%= bag.opened_on || 'Unopened' %></td>
                <td><%= bag.finished_at || 'Unfinished' %></td>
                <% if current_user %>
                    <td class="list-row-action-cell">
                        <%= link_to bag, method: :delete, data: {confirm: 'Are you sure?'},
                                    class: 'btn btn-danger btn-xs pull-right', style: 'margin-left: 5px' do %>
                            <span class='glyphicon glyphicon-remove'></span>
                        <% end %>
                        <%= link_to 'Open Bag', open_bag_path(bag), method: :post, class: 'btn btn-primary btn-xs pull-right' unless bag.opened_on %>
                        <%= link_to 'Finish Bag', finish_bag_path(bag), method: :post, class: 'btn btn-primary btn-xs pull-right' if bag.opened_on && !bag.finished_at %>
                    </td>
                <% end %>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>
<%= paginate @bags %>
<br>

app/views/admin/bags/index.html.erb
<% title "Bags of #{@coffee.name}" %>

<div class="row">
    <div class="col-xs-12">
        <h1 class="index-page-title">
            Bags of <%= link_to @coffee.name, @coffee %>
            <% if current_user %>
                <%= link_to '+ Add Bag', new_coffee_bag_path(@coffee), class: 'btn btn-primary pull-right undo-float' %>
            <% end %>
        </h1>

        <%= render 'list' %>

        <br>
    </div>
</div>

app/views/admin/bags/new.html.erb
<h1>New Bag of <%= @coffee.name %></h1>

<%= render 'form' %>